### ISSUE TITLE
K64F: Build errors

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-ble#11] opened 2016-10-12 14:19 UTC
Following build errors occured when building to K64F.
 
Environment:
Ubuntu 14.04 virtual machine
mbed-cli v.0.9.7
ARM Compiler 5.06 update 4 (build 422)
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529

Windows:
mbed-cli v.0.9.7
Keil uvivion 5.21.1.0
IAR for ARM vesion 7.70.2.11710

* Mbed CLI errors: 
GCC_ARM:
`
[ERROR] In file included from ./mbed-os/features/FEATURE_LWIP/lwip-interface/emac_lwip.c:17:0: ./mbed-os/platform/platform.h:22:19: fatal error: cstddef: No such file or directory #include <cstddef>
`

* Online IDE:
`
Error: 
Cannot open source input file "events/mbed_events.h": No such file or directory in "BLE_HeartRate/source/main.cpp", Line: 17, Col: 33
`

* Export:
mbed export -i uvision5 -m K64F
In windows, following error occured when exporting: 

`
Traceback (most recent call last):
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 229, in export_project
    macros=macros)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 90, in generate_project_files
    exporter.generate()
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\uvision\__init__.py", line 192, in generate
    'device': DeviceUvision(self.target),
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\uvision\__init__.py", line 23, in __init__
    DeviceCMSIS.__init__(self, target)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\cmsis\__init__.py", line 53, in __init__
    raise TargetNotSupportedException("Target not in CMSIS packs")
tools.export.exporters.TargetNotSupportedException: Target not in CMSIS packs
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i uvision5 -m K64F --source ." in "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate"
`

When exporting in Linux and build in windows, all works OK.

* mbed export -i iar -m K64F: 

Exporting in Linux OK, build gives error:
`
Tool Internal Error: 
Internal Error: [CoreUtil/General]: OgElfTypeHandler: Missing type entry for local in B200 events::EventQueue::call<>(void (*)())(f); s: this, <Var 8566>, p, e; t: local [C:\Users\ 
terhei01\work\linux_share\BLE_HeartRate\mbed-os\events\EventQueue.h\175:9-189:5] 

Internal Error: [CoreUtil/General]: OgElfTypeHandler: Missing type entry for local in B200 events::EventQueue::call<>(void (*)())(f); s: this, <Var 8566>, p, e; t: local [C:\Users\ 
terhei01\work\linux_share\BLE_HeartRate\mbed-os\events\EventQueue.h\175:9-189:5] 

Error while running C/C++ Compiler
`

Exporting in Windows gives following error:
`
traceback`` (most recent call last):
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 229, in export_project
    macros=macros)
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project_api.py", line 90, in generate_project_files
    exporter.generate()
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\iar\__init__.py", line 114, in generate
    'debugger': DeviceCMSIS(self.target).debug.replace('-','').upper()
  File "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\export\cmsis\__init__.py", line 53, in __init__
    raise TargetNotSupportedException("Target not in CMSIS packs")
tools.export.exporters.TargetNotSupportedException: Target not in CMSIS packs
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os\tools\project.py -i iar -m K64F --source ." in "C:\Users\terhei01\work\git\oob-mbed-os-example-ble\BLE_HeartRate"
`

* mbed export -i gcc_arm -m K64F and mbed export -i make_gcc_arm -m K64F:
In Linux, exporting ok, build gives following error:
`
Compile: emac_lwip.c
In file included from ../mbed-os/features/FEATURE_LWIP/lwip-interface/emac_lwip.c:17:0:
.././mbed-os/platform/platform.h:22:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
make[1]: *** [mbed-os/features/FEATURE_LWIP/lwip-interface/emac_lwip.o] Error 1
make: *** [all] Error 2
`

* mbed export -i make_iar -m K64F
In windows:
`
/usr/bin/sh: C:/Program: No such file or directory
make: *** [all] Virhe 127
`

**Comment by pan-** [comment] 2016-10-12 16:36
@terhei 

> ARM Compiler 5.06 update 4 (build 422)

This is not supported by mbed-os, 4.9.x series is the one supported.

* LWIP errors are worked on in mbed-os: https://github.com/ARMmbed/mbed-os/pull/2994#issuecomment-253241884
* Other issues related to the exporters and the online IDE are also worked on; outside this repo.

**Comment by terhei** [comment] 2016-10-13 06:23
> This is not supported by mbed-os, 4.9.x series is the one supported.

That sould be mentioned in Pre-Requisites. Now there is link to https://launchpad.net/gcc-arm-embedded where you can download latest version of arm gcc.

Now I found out that this is documented in https://github.com/ARMmbed/mbed-cli "Compiling code ->Toolchain selection". (Not even there in Installation - chapter)

**Comment by MarceloSalazar** [comment] 2016-10-14 15:43
I understand the remaining issue is caused by the Online IDE. This is fixed now and instructions on how to test the beta version of the IDE will be provided for the RC3.

**Closed by MarceloSalazar** 2016-10-14 15:43 UTC
